{"run_number": "1714581037978271", "step_name": "prepare_dataset", "task_id": "2", "attempt_id": 0, "name": "_exception", "content_type": "gzip+pickle-v2", "type": "metaflow.artifact", "sha": "739ec96dda9a4069f21b971d819b7d1ab749c52b", "ds_type": "local", "location": ":root:/home/shashwat/Desktop/flaskrec/.metaflow", "flow_id": "DataFlow", "user_name": "shashwat", "tags": [], "system_tags": ["runtime:dev", "metaflow_version:2.11.10", "user:shashwat", "python_version:3.10.12"], "ts_epoch": 1714581038895}